[package]
name = "robot_map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
noise = "0.9.0"
parking_lot = "0.12.1"
rand = "0.8.5"
rayon = "1.10.0"
